### ISSUE TITLE
豆瓣图书失败Process completed with exit code 1.

### ISSUE THREAD

**Issue by Hao-Gloria** [malinkang/douban2notion#6]
我是图书和观影一起设置的，然而观影没有任何问题，图书我设置了好几次都不成功，具体如下：
3s
Run python -u scripts/update_heatmap.py "book"
***
567e5581-d2ee-44a5-ad68-097c8f873622
fc163e8c-be7d-4748-b4d9-2c89370988bf
901ca57a-6977-47ef-b31b-58a615232830
b0071252-2bf7-4da8-98a7-9c9df44adcac
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: './OUT_FOLDER/notion.svg' -> './OUT_FOLDER/book/1720168701.svg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/douban2notion/douban2notion/scripts/update_heatmap.py", line 30, in <module>
    image_file = move_and_rename_file(type)
  File "/home/runner/work/douban2notion/douban2notion/scripts/update_heatmap.py", line 21, in move_and_rename_file
    shutil.move(source_path, target_path)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './OUT_FOLDER/notion.svg'
Error: Process completed with exit code 1.
我看到报告没有/OUT_FOLDER/book/1720168701.svg这个文件，我查看我的目录后发现有的文件是1720023526.svg。

**Comment by Hao-Gloria** [comment]
补充一下，BOOK_NAME也是无法修改的
